datasets:
  msrvtt:
    train:
      - msrvtt
    val:
      - msrvtt
    test:
      - msrvtt

  msrvtt:
    vis_processor:
      train:
        name: "alpro_video_train"
        n_frms: 16
        image_size: 224
      eval:
        name: "alpro_video_eval"
        n_frms: 16
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"
      eval:
        name: "blip_caption" 