datasets:
    msrvtt_caption:
        data_type: videos
        build_info:
            annotations:
                train:
                    storage: "/storage/student10/vidcaption/LAVIS/datasets/msrvtt/annotations/cap_train.json"
                val:
                    storage: "/storage/student10/vidcaption/LAVIS/datasets/msrvtt/annotations/cap_val.json"
                test:
                    storage: "/storage/student10/vidcaption/LAVIS/datasets/msrvtt/annotations/cap_test.json"
            videos:
                storage: "/storage/student10/vidcaption/LAVIS/datasets/msrvtt/videos"
        vis_processor:
            train:
                name: "alpro_video_train"
                image_size: 224
                n_frms: 16  # Tăng từ 8 lên 16
            eval:
                name: "alpro_video_eval"
                image_size: 224
                n_frms: 16  # Tăng từ 8 lên 16
        text_processor:
            train:
                name: "blip_caption"
            eval:
                name: "blip_caption"

model:
    arch: blip2_timesformer
    model_type: pretrain

    timesformer:
        image_size: 224
        patch_size: 16
        num_frames: 16  # Tăng từ 4 lên 16
        attn_drop_rate: 0.1  # Thêm attn_drop_rate
        drop_rate: 0.1
        drop_path_rate: 0.1
        n_frms: 16  # Tăng từ 4 lên 16

    image_size: 224
    drop_path_rate: 0
    use_grad_checkpoint: True
    vit_precision: "fp16"
    freeze_vit: True
    num_query_token: 128  # Giảm từ 256 xuống 128
    cross_attention_freq: 2  # Thêm cross_attention_freq

    # Pretrained paths
    #pretrained_qformer_path: "https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/BLIP2/blip2_pretrained.pth"
    #timesformer_pretrained: "https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/ALPRO/alpro_msrvtt_qa.pth"

run:
    task: "captioning"
    batch_size_train: 16  # Tăng từ 8 lên 16
    batch_size_eval: 8  # Tăng từ 4 lên 8
    num_workers: 4
    load_gt_from_file: true
    annotation_file: "/storage/student10/vidcaption/LAVIS/cache/msrvtt_caption_gt/msrvtt_caption_test_annotations.json"
    max_epoch: 10  # Tăng từ 20 lên 30
    lr_sched: "linear_warmup_cosine_lr"
    init_lr: 5e-5  # Tăng từ 1e-5 lên 5e-5
    min_lr: 1e-6  # Giảm từ 5e-6 xuống 1e-6

    seed: 42
    output_dir: "output/BLIP2_TimeSformer/pretrain_stage1"

    optimizer:
        name: adamw
        lr: 5e-5  # Giữ nguyên
        weight_decay: 0.01  # Giảm từ 0.05 xuống 0.01
        beta1: 0.9
        beta2: 0.999

    scheduler:
        name: cosine
        num_warmup_steps: 1000  # Giảm từ 2500 xuống 1000

    amp: True
    resume_ckpt_path: null

    evaluate: False
    train_splits: ["train"]
    valid_splits: ["test"]

    device: "cuda"
    world_size: 3
    dist_url: "env://"
    distributed: True

    warmup_steps: 1000  # Giảm từ 5000 xuống 1000