model:
  arch: blip2_timesformer
  model_type: pretrain
  
  # Cấu hình TimeSformer
  vit_model: "timesformer"
  image_size: 224
  num_frames: 8
  drop_path_rate: 0.1
  use_grad_checkpointing: True
  freeze_vit: True
  
  # Cấu hình Q-Former
  num_query_token: 32
  cross_attention_freq: 2
  embed_dim: 768
  max_txt_len: 32

run:
  task: retrieval
  # Tham số tối ưu hóa
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 3e-5
  min_lr: 1e-6
  warmup_lr: 1e-7
  warmup_steps: 1000
  weight_decay: 0.05
  max_epoch: 10
  
  batch_size_train: 32  # Điều chỉnh theo GPU memory
  batch_size_eval: 32
  num_workers: 4
  
  seed: 42
  output_dir: "output/BLIP2_TimeSformer/pretrain"

  amp: True
  resume_ckpt_path: null

  evaluate: False
  train_splits: ["train"]
  valid_splits: ["test"]

  # Phân tán training
  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True
