model:
  arch: pretrain
  load_finetuned: False
  vit_model: timesformer
  pretrained: "/storage/student10/vidcaption/LAVIS/lavis/output/BLIP2_TimeSformer/pretrain_stage1/20250514134/checkpoint_9.pth"
  image_size: 224
  num_frames: 8
  drop_path_rate: 0.1
  use_grad_checkpointing: False
  vit_precision: fp16
  freeze_vit: False
  
  # Q-Former settings
  num_query_token: 128
  cross_attention_freq: 2
  embed_dim: 768
  max_txt_len: 32
    
  timesformer:
    image_size: 224
    patch_size: 16
    attn_drop_rate: 0.1
    drop_rate: 0.1
    num_frames: 8
    drop_path_rate: 0.1

preprocess:
  vis_processor:
    train:
      name: "alpro_video_train"
      image_size: 224
    eval:
      name: "alpro_video_eval"
      image_size: 224
  text_processor:
    train:
      name: "blip_caption"
    eval:
      name: "blip_caption" 
